### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by zerotracex** [Novfensec/SAMPLE-KIVYMD-APP#8]
Your GitHub actions gives below error help please 🥺🥺 
![Screenshot_20241221-195604](https://github.com/user-attachments/assets/8d14f095-4acf-4a31-bcb7-c7c783cee90f)
Please help please 😭😭

**Comment by Novfensec** [comment]
Use `ubuntu-22.04` in place of `ubuntu-latest`

**Comment by Novfensec** [comment]
> Your GitHub actions gives below error help please 🥺🥺 
> ![Screenshot_20241221-195604](https://github.com/user-attachments/assets/8d14f095-4acf-4a31-bcb7-c7c783cee90f)
> Please help please 😭😭

Updated workflow to use `ubuntu-22.04`

**Comment by zerotracex** [comment]
Thank you , trying now

**Comment by Novfensec** [comment]
> Thank you , trying now 

See the latest workflow run at https://github.com/Novfensec/SAMPLE-KIVYMD-APP/actions/runs/12449687586
