### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by arjunet** [Novfensec/SAMPLE-KIVYMD-APP#9]
when I run the workflow, it says: ("ERROR: Could not find a version that satisfies the requirement urllib.request (from versions: none)
```bash
ERROR: No matching distribution found for urllib.request

  STDERR:
# Command failed: ['/opt/hostedtoolcache/Python/3.11.11/x64/bin/python', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=GalaxyViewer', '--bootstrap=sdl2', '--requirements=python3,kivy,sdl2_ttf,pillow,python-vlc,urllib.request,xml.etree.ElementTree,kivymd,kivy-garden', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/runner/work/convert-kivy-to-py/convert-kivy-to-py/.buildozer/android/platform/build-armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SELENIUM_JAR_PATH = '/usr/share/java/selenium-server.jar'
#     CONDA = '/usr/share/miniconda'
#     GITHUB_WORKSPACE = '/home/runner/work/convert-kivy-to-py/convert-kivy-to-py'
#     JAVA_HOME_11_X64 = '/usr/lib/jvm/temurin-11-jdk-amd64'
#     PKG_CONFIG_PATH = '/opt/hostedtoolcache/Python/3.11.11/x64/lib/pkgconfig'
#     GITHUB_PATH = '/home/runner/work/_temp/_runner_file_commands/add_path_51cc8609-855f-4942-8bf2-0a781d2e199e'
#     GITHUB_ACTION = 'buildozer'
#     JAVA_HOME = '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64'
#     GITHUB_RUN_NUMBER = '118'
#     RUNNER_NAME = 'GitHub Actions 1'
#     GRADLE_HOME = '/usr/share/gradle-8.11.1'
#     GITHUB_REPOSITORY_OWNER_ID = '134853141'
#     ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE = '/opt/actionarchivecache'
#     XDG_CONFIG_HOME = '/home/runner/.config'
#     Python_ROOT_DIR = '/opt/hostedtoolcache/Python/3.11.11/x64'
#     DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
#     ANT_HOME = '/usr/share/ant'
#     JAVA_HOME_8_X64 = '/usr/lib/jvm/temurin-8-jdk-amd64'
#     GITHUB_TRIGGERING_ACTOR = 'arjunet'
#     pythonLocation = '/opt/hostedtoolcache/Python/3.11.11/x64'
#     GITHUB_REF_TYPE = 'branch'
#     HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS = '3650'
#     ANDROID_NDK = '/usr/local/lib/android/sdk/ndk/27.2.12479018'
#     BOOTSTRAP_HASKELL_NONINTERACTIVE = '1'
#     PWD = '/home/runner/work/convert-kivy-to-py/convert-kivy-to-py'
#     PIPX_BIN_DIR = '/opt/pipx_bin'
#     STATS_TRP = 'true'
#     GITHUB_REPOSITORY_ID = '908656159'
#     DEPLOYMENT_BASEPATH = '/opt/runner'
#     GITHUB_ACTIONS = 'true'
#     STATS_VMD = 'true'
#     ANDROID_NDK_LATEST_HOME = '/usr/local/lib/android/sdk/ndk/27.2.12479018'
#     SYSTEMD_EXEC_PID = '616'
#     GITHUB_SHA = '832535e684675d34fd40738bdca9054847810f9e'
#     GITHUB_WORKFLOW_REF = 'arjunet/convert-kivy-to-py/.github/workflows/build.yml@refs/heads/main'
#     POWERSHELL_DISTRIBUTION_CHANNEL = 'GitHub-Actions-ubuntu22'
#     RUNNER_ENVIRONMENT = 'github-hosted'
#     STATS_EXTP = 'https://provjobdprod.z13.web.core.windows.net/settings/provjobdsettings-latest/provjobd.data'
#     DOTNET_MULTILEVEL_LOOKUP = '0'
#     GITHUB_REF = 'refs/heads/main'
#     RUNNER_OS = 'Linux'
#     GITHUB_REF_PROTECTED = 'false'
#     HOME = '/home/runner'
#     GITHUB_API_URL = 'https://api.github.com/'
#     LANG = 'C.UTF-8'
#     RUNNER_TRACKING_ID = 'github_aae10165-975c-496e-8df1-6b121f9a6e45'
#     RUNNER_ARCH = 'X64'
#     GOROOT_1_21_X64 = '/opt/hostedtoolcache/go/1.21.13/x64'
#     RUNNER_TEMP = '/home/runner/work/_temp'
#     GITHUB_STATE = '/home/runner/work/_temp/_runner_file_commands/save_state_51cc8609-855f-4942-8bf2-0a781d2e199e'
#     STATS_PIP = 'false'
#     EDGEWEBDRIVER = '/usr/local/share/edge_driver'
#     JAVA_HOME_21_X64 = '/usr/lib/jvm/temurin-21-jdk-amd64'
#     GITHUB_ENV = '/home/runner/work/_temp/_runner_file_commands/set_env_51cc8609-855f-4942-8bf2-0a781d2e199e'
#     GITHUB_EVENT_PATH = '/home/runner/work/_temp/_github_workflow/event.json'
#     INVOCATION_ID = '14b52294344a45c7ac2b851212381756'
#     STATS_D = 'true'
#     GITHUB_EVENT_NAME = 'push'
#     GITHUB_RUN_ID = '12553860684'
#     JAVA_HOME_17_X64 = '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64'
#     ANDROID_NDK_HOME = '/usr/local/lib/android/sdk/ndk/27.2.12479018'
#     GITHUB_STEP_SUMMARY = '/home/runner/work/_temp/_runner_file_commands/step_summary_51cc8609-855f-4942-8bf2-0a781d2e199e'
#     HOMEBREW_NO_AUTO_UPDATE = '1'
#     GITHUB_ACTOR = 'arjunet'
#     NVM_DIR = '/home/runner/.nvm'
#     SGX_AESM_ADDR = '1'
#     GITHUB_RUN_ATTEMPT = '1'
#     STATS_RDCL = 'true'
#     ANDROID_HOME = '/usr/local/lib/android/sdk'
#     GITHUB_GRAPHQL_URL = 'https://api.github.com/graphql'
#     ACCEPT_EULA = 'Y'
#     RUNNER_USER = 'runner'
#     STATS_UE = 'true'
#     USER = 'runner'
#     GITHUB_SERVER_URL = 'https://github.com/'
#     STATS_V3PS = 'true'
#     PIPX_HOME = '/opt/pipx'
#     GECKOWEBDRIVER = '/usr/local/share/gecko_driver'
#     STATS_EXT = 'true'
#     CHROMEWEBDRIVER = '/usr/local/share/chromedriver-linux64'
#     SHLVL = '0'
#     ANDROID_SDK_ROOT = '/usr/local/lib/android/sdk'
#     VCPKG_INSTALLATION_ROOT = '/usr/local/share/vcpkg'
#     GITHUB_ACTOR_ID = '134853141'
#     RUNNER_TOOL_CACHE = '/opt/hostedtoolcache'
#     ImageVersion = '20241215.1.0'
#     Python3_ROOT_DIR = '/opt/hostedtoolcache/Python/3.11.11/x64'
#     DOTNET_NOLOGO = '1'
#     GOROOT_1_23_X64 = '/opt/hostedtoolcache/go/1.23.4/x64'
#     GITHUB_WORKFLOW_SHA = '832535e684675d34fd40738bdca9054847810f9e'
#     GITHUB_REF_NAME = 'main'
#     GITHUB_JOB = 'build'
#     LD_LIBRARY_PATH = '/opt/hostedtoolcache/Python/3.11.11/x64/lib'
#     XDG_RUNTIME_DIR = '/run/user/1001'
#     AZURE_EXTENSION_DIR = '/opt/az/azcliextensions'
#     PERFLOG_LOCATION_SETTING = 'RUNNER_PERFLOG'
#     STATS_VMFE = 'true'
#     GITHUB_REPOSITORY = 'arjunet/convert-kivy-to-py'
#     Python2_ROOT_DIR = '/opt/hostedtoolcache/Python/3.11.11/x64'
#     CHROME_BIN = '/usr/bin/google-chrome'
#     ANDROID_NDK_ROOT = '/usr/local/lib/android/sdk/ndk/27.2.12479018'
#     GOROOT_1_22_X64 = '/opt/hostedtoolcache/go/1.22.10/x64'
#     GITHUB_RETENTION_DAYS = '90'
#     JOURNAL_STREAM = '8:19749'
#     RUNNER_WORKSPACE = '/home/runner/work/convert-kivy-to-py'
#     LEIN_HOME = '/usr/local/lib/lein'
#     LEIN_JAR = '/usr/local/lib/lein/self-installs/leiningen-2.11.2-standalone.jar'
#     GITHUB_ACTION_REPOSITORY = ''
#     PATH = '/home/runner/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/hostedtoolcache/Python/3.11.11/x64/bin:/opt/hostedtoolcache/Python/3.11.11/x64:/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     RUNNER_PERFLOG = '/home/runner/perflog'
#     GITHUB_BASE_REF = ''
#     GHCUP_INSTALL_BASE_PREFIX = '/usr/local'
#     CI = 'true'
#     SWIFT_PATH = '/usr/share/swift/usr/bin'
#     ImageOS = 'ubuntu22'
#     STATS_D_D = 'true'
#     GITHUB_REPOSITORY_OWNER = 'arjunet'
#     GITHUB_HEAD_REF = ''
#     date = '20241231'
#     GITHUB_ACTION_REF = ''
#     STATS_D_TC = 'true'
#     GITHUB_WORKFLOW = 'Android Build'
#     DEBIAN_FRONTEND = 'noninteractive'
#     GITHUB_OUTPUT = '/home/runner/work/_temp/_runner_file_commands/set_output_51cc8609-855f-4942-8bf2-0a781d2e199e'
#     AGENT_TOOLSDIRECTORY = '/opt/hostedtoolcache'
#     _ = '/opt/hostedtoolcache/Python/3.11.11/x64/bin/buildozer'
#     PACKAGES_PATH = '/home/runner/.buildozer/android/packages'
#     ANDROIDSDK = '/home/runner/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/runner/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```

**Comment by Novfensec** [comment]
That is an error related to the requirements you specify in `buildozer.spec` not related to this workflow. You need to check the names of requirements you specify in `buildozer.spec`. In your case the package name should be `urllib3` not urllib.request.
By the way urllib is already there in python no need to specify separately.

**Comment by Novfensec** [comment]
I checked your buildozer.spec;

```yaml
requirements = python3,kivy,sdl2_ttf,pillow,python-vlc,urllib.request,xml.etree.ElementTree,kivymd,kivy-garden
```

Replace above with below code;
```yaml
requirements = python3,kivy,sdl2_ttf,pillow,python-vlc,kivymd,kivy-garden
```

If you are using kivymd latest version then below requirements;
```yaml
requirements = python3,kivy,sdl2_ttf,python-vlc,kivy-garden,https://github.com/kivymd/KivyMD/archive/master.zip, pillow, materialyoucolor, exceptiongroup, asyncgui, asynckivy
```


**Since you are not using kivymd you dont need to have that in requirements**
Use below for your app maintaining app size;

```yaml
requirements = python3,kivy,sdl2_ttf,pillow,kivy-garden
```

**Comment by arjunet** [comment]
I will try it.

**Comment by arjunet** [comment]
I fixed it, it worked just now.

**Comment by Novfensec** [comment]
> I fixed it, it worked just now.
> 

That's nice!

Make sure to specify only those requirements that are installed from pypi and also required by your app as I saw your app doesn't use kivymd and you dont need it.

But may be in future you might have to use it so just chill.

**Comment by arjunet** [comment]
I put kivymd in requirements because, I was following this : https://www.youtube.com/watch?v=WQ0oNpsTJus&t=232s. The guy also said to use pillow to prevent crashing, but although now it works, my apk just crashes, PLEASE HELP PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Novfensec** [comment]
> I put kivymd in requirements because, I was following this : https://www.youtube.com/watch?v=WQ0oNpsTJus&t=232s. The guy also said to use pillow to prevent crashing, but although now it works, my apk just crashes, PLEASE HELP PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!

Join this discord server for my assistance.
https://discord.gg/U9bfkD6A4c


Use the below website to debug the apk.
https://appetize.io

Or use android studio.

**Comment by Novfensec** [comment]
> I put kivymd in requirements because, I was following this : https://www.youtube.com/watch?v=WQ0oNpsTJus&t=232s. The guy also said to use pillow to prevent crashing, but although now it works, my apk just crashes, PLEASE HELP PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!

I saw in buildozer.spec `android.archs` you have to put `armeabi-v7a` and `arm64-v8a`.

**Please clear all the old caches saved on github under action tab left panel to rebuilt all libraries afresh as buildozer won't update by itself.**

**Comment by arjunet** [comment]
I will try, PLEASE STAY HERE BECAUSE IT MAY HAVE MORE ERRORS!!!!!!!!! Thank you :)

**Comment by Novfensec** [comment]
> I will try, PLEASE STAY HERE BECAUSE IT MAY HAVE MORE ERRORS!!!!!!!!! Thank you :)
> 

Also put `android.api = 35` required by android>14

It is a commented out line in `buildozer.spec`.

**Comment by arjunet** [comment]
IS THERE ANYTHING ELSE, I JUST FINISHED BUILDING FOR PAST HOUR, please any other advice before I start building, i dont want to waste time.

**Comment by Novfensec** [comment]
> IS THERE ANYTHING ELSE, I JUST FINISHED BUILDING FOR PAST HOUR, please any other advice before I start building, i dont want to waste time.

First check if it works on the online emulator and resolve all the errors given by the apk. It will take time if you want to indulge in all this. There might be some errors in your python code and other things during running of apk.

Also use `p4a.branch = develop`

**Comment by Novfensec** [comment]
@arjunet You dont have to remove cache all times just when you use a new branch of python for android or add or remove something in `android.archs` that requires a fresh build.

**Comment by arjunet** [comment]
OK, I will try. Thanks for advice :)

**Comment by arjunet** [comment]
It STILL crashes

**Comment by Novfensec** [comment]
> It STILL crashes

I debugged it myself.

vlc is not a cross platform. Use ffmpeg or ffpyplayer for video loading or package the required vlc c++ files withing the app.

Its uses native vlc libraries which are available only on desktop platforms!!

The bindings use ctypes to directly call the libvlc dynamic lib, and the code is generated from the include files defining the public API. The same module should be compatible with various versions of libvlc 3.*. However, there may be incompatible changes between major versions.

You may switch to another native video player provided by kivy itself. Or see more about ffpyplayer on the internet.

You need to know about java classes I mean java programming language to implement from core the video player api if you want complete customization.

**Comment by arjunet** [comment]
" package the required vlc c++ files withing the app.", how do I do that?

**Comment by Novfensec** [comment]
> " package the required vlc c++ files withing the app.", how do I do that? 

Read vlc documentation and source code. If vlc is installed go through all the files folders in the directory where it is installed.

Contact the owner of the codebase of vlc.

I mean you need to package vlc with your app as it is a requirement. Everything from scratch. You need to discuss with known developers of vlc on how they packaged thier vlc files in their android vlc media player app. And do similar things in python for that. 

You can create your own module named vlc-pythonforandroid to provide users with prebundled c++ files required by vlc media player.

**Comment by Novfensec** [comment]
@arjunet 

Reference repository of their android app: https://github.com/videolan/vlc-android

They have provided some build instructions you may follow.

# Build

## Native libraries are published on bintray. So you can:
- Build the application and get libraries via gradle dependencies (JVM build only)
- Build the whole app (LibVLC + Medialibrary + Application)
- **Build LibVLC only, and get an .aar package**

Creating an aar package is also a way. And then use this aar vlc build for the main app. Make it a requirement for the app and ask users to download this plugin on play store.

**Comment by arjunet** [comment]
I barely know how to code, and I dont have a lot of experience with c++, or kivy.

**Comment by Novfensec** [comment]
> I barely know how to code, and I dont have a lot of experience with c++, or kivy.

Then only go for basic things for now and when you get comfortable join the real party.

**Comment by arjunet** [comment]
May you provide an updated main.py, and/or buildozer.spec file?

**Comment by Novfensec** [comment]
> I barely know how to code, and I dont have a lot of experience with c++, or kivy.

Try this official cli for kivy apps like expo for react native;

KvDeveloper: https://github.com/Novfensec/KvDeveloper

Go through the readme.

**Comment by Novfensec** [comment]
> May you provide an updated main.py, and/or buildozer.spec file?

I'm busy on a commercial chat app for APRSD : https://github.com/craigerl/aprsd ham radio owners in US built using kivy and kivymd etc. So I might not be able to help.

**Comment by arjunet** [comment]
It's okay.

**Comment by arjunet** [comment]
Hey, It works now, but when I click on one of the buttons, it doesn't play any stream

**Comment by arjunet** [comment]
CAN YOU HELP ME HERE, I now using ffpyplayer, but when I try to play a stream, it just closes the app.

**Comment by Novfensec** [comment]
> CAN YOU HELP ME HERE, I now using ffpyplayer, but when I try to play a stream, it just closes the app.
> 

This place is to help you with this issue join the official kivy discord and ask for help any time you want. There are 5 support channels.

**Comment by arjunet** [comment]
Hi again, I'm making another Kivy app, but I don't know my requirements. I was using PyCharm to create/test the app. I dont know my requirements. Can you see whats my requirements? My file: 

[main.txt](https://github.com/user-attachments/files/19324816/main.txt)

**Comment by arjunet** [comment]
@Novfensec @Novfensec

**Comment by Novfensec** [comment]
> @Novfensec @Novfensec 

Your requirements are python3, kivy==2.3.0, pyrebase, firebase_admin, pillow

**Comment by arjunet** [comment]
My app is crashing. I used ADB to see the issue, but I don't understand. Here is my adb debug: 

[debug.txt](https://github.com/user-attachments/files/19331345/debug.txt)

**Comment by Novfensec** [comment]
> My app is crashing. I used ADB to see the issue, but I don't understand. Here is my adb debug: 
> 
> [debug.txt](https://github.com/user-attachments/files/19331345/debug.txt)

## no module named urllib3.contrib.appengine

The `appengine` module is a Python module that provides support for the Google App Engine platform. It includes classes and functions for interacting with the App Engine APIs, such as the datastore, the blobstore, and the memcache.

The `appengine` module is not included in `urllib3` because it is not a general-purpose module. It is designed specifically for use with the Google App Engine platform.

## solution 
Install appengine module separately.
`pip install appengine`

Or use **pyrebase4** instead of pyrebase.


Add appengine or **pyrebase4** to buildozer requirements.

Do a clean build from scratch.

**Comment by arjunet** [comment]
My build failed. My error IN THE GITHUB ACTIONS: 

[debug.txt](https://github.com/user-attachments/files/19339899/debug.txt)

**Comment by arjunet** [comment]
how to "Install appengine module separately.
pip install appengine"??

**Comment by arjunet** [comment]
@Novfensec @Novfensec

**Comment by Novfensec** [comment]
> how to "Install appengine module separately.
> pip install appengine"??

You are using grpcio which is not a pure python package and needs a recipe to build.

**Comment by Novfensec** [comment]
> how to "Install appengine module separately.
> pip install appengine"??

Come to discord if you have an account.

**Comment by arjunet** [comment]
ERROR: Could not find a version that satisfies the requirement appengine (from versions: none)
ERROR: No matching distribution found for appengine

**Comment by arjunet** [comment]
@Novfensec @Novfensec
